server:
  port: 7007
spring:
  application:
    name: api-gateway
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://server1:7000/eureka/

  instance:
    hostname: localhost
zuul:
  routes:
    e-p:
      path: /e-p/**
      serviceId: eureka-provider1
    e-c:
      path: /e-c/**
      serviceId: eureka-consumer1

yxwfilter:
  ip:
    whitelist: 192.168.133.1,192.168.255.1,192.168.136.1,192.168.72.1,172.20.10.8
    whitelistenabled: true
